---
- include: setup.yml
- include: stop_seeder_and_tracker.yml
- include: stop_all_peers.yml
- include: rm_tgz.yml
- include: start_tracker.yml
- include: create_torrent.yml
- include: start_seeder.yml
- include: deploy.yml
- include: stop_seeder_and_tracker.yml

